### ISSUE TITLE
Add staff bios to the staff previews instead of linking to the Goodle Staff Profiles Document

### ISSUE THREAD

**Issue by Faryab** [eecs370/eecs370.github.io#1]
Currently when clicking one of the staff names we hyperlink to the Google Drive staff profiles document.

Historically we never had staff on the website, so we linked to the staff profiles document directly. Now that we have the staff highlighted it is kind of redundant to link to the document upon clicking one of the names.

I think it would be easier UI to just add the bio previews on highlight, like how the contact info and emails are currently added.

**Comment by jackphong** [comment]
Done - I decided to just add the bios under the pictures.
