### ISSUE TITLE
Update specs to use markdown file rather than HTML

### ISSUE THREAD

**Issue by alexewu** [eecs370/eecs370.github.io#10]
@jackphong I added the markdown files that generated the HTML files from Winter 2020. I added some TODOs to help with updating the site. Just be extra careful that all the specs have the right links and COVID-semester info. This should make updating specs a lot easier overall. Feel free to reach out with any questions.

This will also update the specs to use the newest version of the primer spec :)

**Comment by jackphong** [comment]
Great, thanks so much!
