### ISSUE TITLE
Update Project Specs to be more explicit about library/header usage.

### ISSUE THREAD

**Issue by Faryab** [eecs370/eecs370.github.io#12]
Based on Mason's request from Slack:

Mason: "What is our policy on library headers for projects? Can they use any? Can they make their own .h file? When I took the course, the autograder wouldn't accept my .h file but what about others?"

Faryab: "Any standard library which compiles using the specified gcc commands in the spec is allowed. (But mostly unnecessary)"

Adding the above information to the project specs.

**Comment by jackphong** [comment]
Should be added now!
