### ISSUE TITLE
Make calendar wider to avoid event names wrapping

### ISSUE THREAD

**Issue by danlliu** [eecs370/eecs370.github.io#14]
<img width="684" alt="Screen Shot 2021-02-08 at 09 59 49" src="https://user-images.githubusercontent.com/66093915/107237118-62798580-69f4-11eb-8203-3a8e036b531b.png">
A few examples of event names being cut off are:
- Mason's OH (Tuesday 2:30)
- Group OH - Daniel (Wednesday 1:30)
- Mason's Post-Discussion OH and OH (Friday afternoon)
Seems like these are due to the column width being too small, if it'd be possible to make the calendar a bit wider that would improve readability.

**Comment by jackphong** [comment]
Since you can't change the calendar width directly, I've added a new button to choose between a 4day / 7day view.
