### ISSUE TITLE
Update P1s Spec

### ISSUE THREAD

**Issue by Faryab** [eecs370/eecs370.github.io#15]
We never explicitly tell students to follow a text/data section format in Project 1. This can lead to students submitting test cases which result in invalid lc2k instructions being executed.

See [full explanation here.](https://piazza.com/class/kjvo5f629u23cu?cid=1061). Here is the [auto-grader submission](https://autograder.io/web/project/922?current_tab=student_lookup&current_student_lookup=227006) and specific [LOC](https://github.com/eecs370/project_1s/blob/master/src/inst_simulator.c#L206) which causes the behavior.

Currently we talk about [submitting valid test cases](https://eecs370.github.io/projects/p1_spec.html#5-behavioral-simulator-40) but it is unclear whether mixing up `.fill`s and instructions is valid or not. Instead we should add phrasing which clarifies valid test cases being ones which eventually halt and do not ever execute a `.fill`

**Comment by Faryab** [comment]
@jackphong  I will resolve this after the p1 cycle is over. This is just for tracking purposes.

**Comment by Faryab** [comment]
Also adding to this issue.

Add an updated `gcc` command which make something which isn't `a.out`, but a name of the student's choosing, like how it's specified in the [p2 spec.](https://eecs370.github.io/projects/p2_spec.html#6-compiling-the-project).

**Comment by jbaileyhandle** [comment]
What's the status of this issue?
