### ISSUE TITLE
Video Reviews link should redirect directly to Youtube channel/playlist

### ISSUE THREAD

**Issue by hdsatam** [eecs370/eecs370.github.io#2]
Right now, the Video Reviews link directs to another page that has a list of the videos on the 370 Youtube channel. It would be much easier to just have the link directly send users to the channel, especially since this dedicated Video Reviews page has very little content on it to begin with.

**Comment by jackphong** [comment]
Done - https://github.com/eecs370/eecs370.github.io/commit/4bdca2d3846aa50c50327893adf3e082434eca1f
