### ISSUE TITLE
Make P2 Spec More Readable

### ISSUE THREAD

**Issue by Faryab** [eecs370/eecs370.github.io#22]
A student was confused by the [examples presented in the spec](https://eecs370.github.io/projects/p2_specs.html#9-sample-test-cases). See [Piazza post](https://piazza.com/class/kjvo5f629u23cu?cid=1328) here.

I can see how the confusion arises. Not sure what the best way to make these clearer is.

**Comment by jackphong** [comment]
Proposed Changes here #23
