### ISSUE TITLE
[Primer Spec] Build a preview of the website with every PR

### ISSUE THREAD

**Issue by seshrs** [eecs370/eecs370.github.io#37]
Hi there! 👋  I build and maintain [Primer Spec](https://github.com/eecs485staff/primer-spec), the theme used by EECS 370 specs.

Over the past year, I noticed that it's not always easy to visualize changes made to course websites or project specs in a Pull Request, especially when a lot of content has changed at once. I created a service called _Primer Spec Preview_ to help make these PRs for course websites easier to review. **The service is used by EECS 280 and EECS 485**, and I'm happy to help onboard EECS 370's website too!

Here's how Primer Spec Preview works:
- A staff member makes a branch/fork with changes to the website, then creates a Pull Request.
- A GitHub Actions workflow runs, which invokes the [_Upload to Primer Spec Preview_ action](https://github.com/seshrs/upload-to-primer-spec-preview). Note that [GitHub Actions](https://github.com/features/actions) is free to run, especially for public repositories.
- The workflow builds the website preview and uploads it to a server that I host at https://preview.sesh.rs. (Builds on this server are periodically deleted.)
- Finally, the workflow posts a comment in the Pull Request with a URL linking to the website preview. Now, other staff members can visit this URL to see what the website would look like after merging the PR!

---

Integrating with Primer Spec Preview is not too hard!
- First, I'll need to email a staff member with "admin" permissions on this repository with instructions to add a [GitHub Secret](https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository).
- Next, I can create a Pull Request that adds a GitHub Actions workflow to actually build and upload the preview. The workflow would be very similar to the one described [here](https://github.com/seshrs/upload-to-primer-spec-preview#usage-with-jekyll-site).

If you're interested, could you let me know who I should email with instructions to add the GitHub secret?

Let me know if you have questions about any of this 😃

**Comment by jackphong** [comment]
Sorry about the long wait! I sent you an email.
