### ISSUE TITLE
Revert spec example for project 2 after deadline

### ISSUE THREAD

**Issue by jbaileyhandle** [eecs370/eecs370.github.io#39]
Spec example was changed to matched bugged autograder version. We should fix this after the deadline.
main.as (0_0.as?) 2nd instructions should be:
lw 0 4 SubAdr
instead of
lw 0 7 SubAdr

**Comment by nelsontm** [comment]
Note: we need to update the starter code folder also

**Comment by jbaileyhandle** [comment]
Fixed here:
https://github.com/eecs370/eecs370.github.io/commit/03b863922b36776168ef3c5348a09f68e3206782#diff-66597133aa8149e9c63dc67ebcf284ac74beb805e4eee8b34d47f017bb5475fd

Also fixed starter code.
