### ISSUE TITLE
Misleading Project Deadline

### ISSUE THREAD

**Issue by Faryab** [eecs370/eecs370.github.io#7]
![image](https://user-images.githubusercontent.com/40459661/105109282-15358280-5ade-11eb-88fd-97b5ba86fd35.png)

There are different deadlines for different parts.

**Comment by danlliu** [comment]
I guess an easy way to fix this would just be have the label say "P1A due Feb 4th 11:55 pm ET", then change it to say "P1L due ...", etc

**Comment by jackphong** [comment]
Due date should be more clear now : 
![image](https://user-images.githubusercontent.com/46696737/105112093-42f3da80-5a90-11eb-8a09-99d39dd4cab0.png)
