### ISSUE TITLE
Add Homework Listing to Website

### ISSUE THREAD

**Issue by latifisalar** [eecs370/eecs370.github.io#9]
It would be great if we can list the files in public folder of homeworks in the website next to the projects.

**Comment by jackphong** [comment]
Done - added homework link on the navbar. Do you think we should also add a section for homework in the website or is this enough?

**Comment by latifisalar** [comment]
I was actually thinking a google folder listing for homework documents next to the projects section in the website. Similar to what we had in the old website. But, if you think it is gonna make the website too cluttered, we can just keep the link in the navbar.

**Comment by jackphong** [comment]
I tried embedding it like the old website did, but I ended up having some permission issues with the g-drive folder. Closing for now, until we can resolve those issues (maybe making the HW folder public could fix the issue.)
